version: "2"
linters:
  enable:
    - bodyclose
    - exhaustive
    - funcorder
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - misspell
    - modernize
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - common-false-positives
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
  settings:
    goimports:
      local-prefixes:
        - github.com/kpumuk/lazykiq
