version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/kpumuk/lazykiq
  mod: mod

builds:
  - main: ./cmd/lazykiq
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=nodbus
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -X main.Date={{ .Date }}
      - -X main.BuiltBy=goreleaser

archives:
  - name_template: >-
      lazykiq-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - '.*\[docs\]$'
      - "^test:"
      - '.*\[test\]$'
      - "^lint:"
      - '.*\[lint\]$'
      - "^chore"
      - '.*\[chore\]$'
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

aurs:
  - name: lazykiq-bin
    git_url: "ssh://aur@aur.archlinux.org/lazykiq-bin.git"
    private_key: "{{ .Env.AUR_KEY }}"
    maintainers:
      - "Dmytro Shteflyuk <kpumuk@kpumuk.info>"
    description: "A rich terminal UI for Sidekiq."
    homepage: "https://github.com/kpumuk/lazykiq"
    license: "MIT"
    package: |-
      install -Dm755 "./lazykiq" "${pkgdir}/usr/bin/lazykiq"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/lazykiq/LICENSE"

homebrew_casks:
  - name: lazykiq
    description: "A rich terminal UI for Sidekiq."
    homepage: "https://github.com/kpumuk/lazykiq"
    binaries:
      - lazykiq
    repository:
      owner: kpumuk
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: false
