pre-push:
  jobs:
    - name: packages audit
      tags:
        - security
      run: mise exec golang -- go tool golang.org/x/vuln/cmd/govulncheck ./...

    - name: gems audit
      tags:
        - security
      run: mise exec ruby -- bundle audit
      root: "demo/"

pre-commit:
  parallel: true
  fail_on_changes: "always"
  jobs:
    - name: lint
      glob:
        - ".golangci.yml"
        - "*.go"
      run: mise run lint --fix

    - name: rubocop
      glob:
        - "demo/**/*.rb"
        - "demo/Gemfile*"
      run: mise exec ruby -- bundle exec standardrb --fix
      root: "demo/"
